version: '3'
services:
  app1:
    image: nginx:latest
    volumes:
      - ~/workspace/docker-k8s-lecture/website:/usr/share/nginx/html
    ports:
      - 8080:80
  app2:
    image: nginx:latest
    volumes:
      - ~/workspace/docker-k8s-lecture/website:/usr/share/nginx/html
    ports:
      - 3000:80

